(source gnu)
(source melpa)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")

;; from myself

(depends-on "init-loader")
(depends-on "key-chord")
(depends-on "redo+")
(depends-on "zlc")
(depends-on "elscreen")
(depends-on "quickrun")

;; my
(depends-on "pickup")
(depends-on "ffap-python")
(depends-on "anything-vcs-project")
;; language
(depends-on "paredit")
(depends-on "go-eldoc")
(depends-on "go-mode")
(depends-on "ghc")
(depends-on "markdown-mode")
(depends-on "haskell-mode")
(depends-on "tuareg")
(depends-on "haxe-mode")
;(depends-on "flymake")
;(depends-on "flymake-go")
(depends-on "flymake-cursor")
(depends-on "flymake-ruby")
(depends-on "typescript")
;;
(depends-on "pophint")

;; not used?
(depends-on "autopair")
(depends-on "bm")
(depends-on "yasnippet")

;; obsolete?
(depends-on "anything")
(depends-on "anything-match-plugin")

