#!/bin/bash

mkdir -p 3rdparty
pushd 3rdparty

wget -nc http://launchpadlibrarian.net/61970301/python-mode.el
test $? = 0 && wget -nc "http://chrispoole.com/mint/pepper/orderedlist/downloads/download.php?file=http%3A//chrispoole.com/downloads/ac-python.el" -O ac-python.el
test $? = 0 && wget -nc http://cx4a.org/pub/auto-complete/auto-complete-1.3.1.tar.bz2 && tar jxvf auto-complete-1.3.1.tar.bz2 && cd auto-complete-1.3.1 && make byte-compile && cd ../

test $? = 0 && touch .downloaded
popd